### ISSUE TITLE
Better pkg name

### ISSUE THREAD

**Issue by sckott** [sckott/scrubr#1]
any ideas?

**Comment by Pakillo** [comment]
I like the name! But I wonder if these functions could rather be integrated in spocc package?

**Comment by sckott** [comment]
@Pakillo good point about spocc. 

spocc did have data cleaning utilties, but those and graphics stuff have been moved to `spoccutils` - But, i've been meaning to make data cleaning better in spoccutils, but hadn't done so yet, and now I think that it might be best to have a sep package for data cleaning, that isn't tied to a specific package. I kinda fall in line with the unix philosophy 

e.g., there are data cleaning tasks that could be useful for any species occurrence dataset, and would be nice to not have to load all that other stuff that spocc/spoccutils depends on - 

from development perspective separating them is nicer too so we can use this as a dependency in other pkgs if needed. 

for spoccutils, we can import this pkg and then tweak things to work around the classes in that pkg

**Comment by Pakillo** [comment]
Agreed. Thanks for the explanation!
